# Generated by Django 5.0.2 on 2025-11-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(max_length=100)),
                ('fecha_realizacion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=255)),
                ('publico_estudiantes', models.BooleanField(default=False)),
                ('publico_maestros', models.BooleanField(default=False)),
                ('publico_general', models.BooleanField(default=False)),
                ('programa_educativo', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable_id', models.IntegerField()),
                ('responsable_tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(max_length=300)),
                ('cupo_maximo', models.IntegerField()),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
